// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwqaiuWtaMVPGl32Ut-dRlNCRaiHgQgw',
    appId: '1:409129836860:web:5143f2bdbe37939d2c3e39',
    messagingSenderId: '409129836860',
    projectId: 'blamics-finance-9f285',
    authDomain: 'blamics-finance-9f285.firebaseapp.com',
    storageBucket: 'blamics-finance-9f285.firebasestorage.app',
    measurementId: 'G-6235QR6FN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHcToGOpB5kCwrnOHSBs8fgToWWvkrHk',
    appId: '1:409129836860:android:25e6e329229d2f982c3e39',
    messagingSenderId: '409129836860',
    projectId: 'blamics-finance-9f285',
    storageBucket: 'blamics-finance-9f285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfiDzXPFNNChOhNXKsStR4djYkiOAoEwY',
    appId: '1:409129836860:ios:61a70b8a99bdea632c3e39',
    messagingSenderId: '409129836860',
    projectId: 'blamics-finance-9f285',
    storageBucket: 'blamics-finance-9f285.firebasestorage.app',
    iosBundleId: 'com.blamics.blamicsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfiDzXPFNNChOhNXKsStR4djYkiOAoEwY',
    appId: '1:409129836860:ios:61a70b8a99bdea632c3e39',
    messagingSenderId: '409129836860',
    projectId: 'blamics-finance-9f285',
    storageBucket: 'blamics-finance-9f285.firebasestorage.app',
    iosBundleId: 'com.blamics.blamicsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFwqaiuWtaMVPGl32Ut-dRlNCRaiHgQgw',
    appId: '1:409129836860:web:26aeffa7d17a03a32c3e39',
    messagingSenderId: '409129836860',
    projectId: 'blamics-finance-9f285',
    authDomain: 'blamics-finance-9f285.firebaseapp.com',
    storageBucket: 'blamics-finance-9f285.firebasestorage.app',
    measurementId: 'G-HQCNFQY1H8',
  );
}
